# Generated by Django 4.2.1 on 2024-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="members",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
